### ISSUE TITLE
[Source Code]: Update engine logging instances

### ISSUE THREAD

**Issue by lucasstarsz** [fastjengine/FastJ#167]
### What's Up?

Many uses of `FastJEngine#log/warning/etc` still make use of string concatenation -- these methods provide a useful formatting system, and should be updated as such.

### Code of Conduct

- [X] I agree to follow FastJ's Code of Conduct

**Comment by YeffyCodeGit** [comment]
Seems pretty simple, could I take this?

**Comment by lucasstarsz** [comment]
> Seems pretty simple, could I take this?

Sure! Make a pr with your changes.
