### ISSUE TITLE
[Feature Request]: Implement addScenes() function

### ISSUE THREAD

**Issue by YeffyCodeGit** [fastjengine/FastJ#178]
### Origins of the Feature

Currently, to add multiple scenes, you need to call the `SceneManager.addScene()` function multiple times. If many scenes need to be added, this can get messy quickly.

### The New Feature Idea(s)

Implement a `addScenes()` function which takes in a list of scenes, and adds all the scenes at once. This will make it easier to add many scenes with one function.

### Alternatives

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lines-of-codes** [comment]
also, I think that It'd be great if it has both `addScenes(Scene...)` and `addScenes(List<Scene>)` (or `addScenes(Scene[])`)

**Comment by YeffyCodeGit** [comment]
Thats a good idea, ill remember to do that!
