### ISSUE TITLE
[Documentation] Source Code link in Maven is broken

### ISSUE THREAD

**Issue by mellobacon** [fastjengine/FastJ#53]
## The Outdated/Incorrect Information
The link to the source code in [Maven](https://search.maven.org/artifact/io.github.lucasstarsz.fastj/fastj-library/1.5.0-SNAPSHOT-1/jar) doesnt work. Its currently https://tech.fastj which bring me to 
![image](https://user-images.githubusercontent.com/42365887/125386460-f368da00-e361-11eb-9ee9-2b4947f6bdbb.png)

## Suggestions
I believe its supposed to be https://fastj.tech.

**Comment by lucasstarsz** [comment]
Fixed in #54.

**Comment by lucasstarsz** [comment]
Fixed in #54.
