### ISSUE TITLE
[Bug] Unusable Quit Button and Resizing when initialized on New window

### ISSUE THREAD

**Issue by lines-of-codes** [fastjengine/FastJ#57]
## Platform Info
_Place an `x` in the box(es)_ `[x]` _that the issue occurs on (or that you've found the issue on)_
- [x] Windows
  - Version: Windows 10 (Build 1909)
- [x] Mac OS
  - Version: _e.g. High Sierra 10.13.6_
- [x] Linux
  - Distro: _e.g Linux Mint_
  - Version: _e.g. 20.1_

## Describe the Bug
_A clear and concise description of what the bug is._
I'm making a Swing UI for adjusting window resolution and Other settings.
But when I run the Code, I pressed play, The game window appears properly. But I can't exit out of the Game using the `x` button on the Window border.
And it messed up the Window resizing as well.

## Expected Behavior
_A clear and concise description of what you expected to happen._
Exit the Java program peacefully. And can resize like normal.

## How to Reproduce the Bug
_Steps to reproduce the behavior:_
1. Use my code (Available to the public soon)
2. Build and run it
3. Press play
4. The game window will popup
5. Try resizing and Press `x` on the Window border.

## Media Aid
_If applicable, add screenshots/GIFs/videos to help explain your problem._

### Messed up resizing
https://user-images.githubusercontent.com/49134472/125572509-6f037792-153b-41ca-818f-8eab00b2759d.mp4

(Video provided by: [lucasstarsz](https://github.com/lucasstarsz))

## Additional context
_Additional context not provided above._

**Comment by lucasstarsz** [comment]
I'll have to leave this to a future update of FastJ, as 1.5.0 is right around the corner. With that said, this is a peculiar issue for sure -- displays and display management will definitely need to be a major focus of the next version.

**Comment by lucasstarsz** [comment]
This feature is properly available in [FastJ 1.6.0-SNAPSHOT-3](https://github.com/fastjengine/FastJ/releases/tag/1.6.0-SNAPSHOT-3). Please give it a try and see if that helps out your issue!

**Comment by lines-of-codes** [comment]
Yeah, I've tried it and it's pretty cool \:p

**Comment by lucasstarsz** [comment]
Glad to hear it! 😄
On that note, if you don't have any more issues feel free to close the issue. Otherwise, it'll be closed when 1.6.0 is released.
