### ISSUE TITLE
[Documentation] Add package-info files to each fastj package

### ISSUE THREAD

**Issue by lucasstarsz** [fastjengine/FastJ#61]
FastJ's packages each lack descriptors for what they relate to. With the engine on the rise, it would make sense to provide a general run-down of what each of the packages contain.

The following packages need to be covered:
- [x] `tech.fastj.engine`
    - [x] `tech.fastj.engine.internals`
- [x] `tech.fastj.graphics`
    - [x] `tech.fastj.graphics.display`
    - [x] `tech.fastj.graphics.game`
    - [x] `tech.fastj.graphics.gradients`
    - [x] `tech.fastj.graphics.io`
    - [x] `tech.fastj.graphics.ui`
    - [x] `tech.fastj.graphics.util`
- [x] `tech.fastj.input`
    - [x] `tech.fastj.input.keyboard`
    - [x] `tech.fastj.input.mouse`
- [x] `tech.fastj.math`
- [x] `tech.fastj.systems`
    - [x] `tech.fastj.systems.audio`
    - [x] `tech.fastj.systems.behaviors`
    - [x] `tech.fastj.systems.control`
    - [x] `tech.fastj.systems.fio`
    - [x] `tech.fastj.systems.tags`

Suggest changes or fixes below.

**Comment by YeffyCodeGit** [comment]
I'm back after my little hiatus, you think I could take this?

**Comment by lucasstarsz** [comment]
> I'm back after my little hiatus, you think I could take this?

Welcome back! Feel free to give it a try! 👍🏾

**Comment by YeffyCodeGit** [comment]
I've already finished writing the docs for the main packages, have yet to do for the sub-packages though. Is there any specific style of writing or anything I need to follow for the docs? Because I can't help but notice that the docs I've written are much smaller than yours.

**Comment by lucasstarsz** [comment]
> I've already finished writing the docs for the main packages, have yet to do for the sub-packages though. Is there any specific style of writing or anything I need to follow for the docs? Because I can't help but notice that the docs I've written are much smaller than yours.

In general, I would try to keep the descriptions for the packages short and to the point. Obviously they need to tell enough information so that the reader can understand what the classes inside are, but they shouldn't each be an essay.

Regardless, I'll be sure to help guide you in the right direction when you eventually make your pull request 👍🏾

**Comment by YeffyCodeGit** [comment]
That's fair. Pull request is coming soon! 👀

**Comment by YeffyCodeGit** [comment]
Got a pull request! 
https://github.com/fastjengine/FastJ/pull/112
