### ISSUE TITLE
[Bug] Stretched display

### ISSUE THREAD

**Issue by lines-of-codes** [fastjengine/FastJ#62]
## Platform Info
_Place an `x` in the box(es)_ `[x]` _that the issue occurs on (or that you've found the issue on)_
- [x] Windows
  - Version: Windows 10 (Build 1909)
- [ ] Mac OS
  - Version: _e.g. High Sierra 10.13.6_
- [ ] Linux
  - Distro: _e.g Linux Mint_
  - Version: _e.g. 20.1_

## Describe the Bug
_A clear and concise description of what the bug is._
I tried running FastJ in 800x600 resolution, Then I found out that the Text is stretched and smaller than it should compare to running at 1280x720 resolution.

## Expected Behavior
_A clear and concise description of what you expected to happen._
I expect the Text to display properly, With the same size when displayed on 1280x720 resolution.

## How to Reproduce the Bug
_Steps to reproduce the behavior:_
1. Use the following code to initialize FastJ:
```java
FastJEngine.init(gameName, this);
FastJEngine.configureViewerResolution(new Point(800, 600));
FastJEngine.run();
```
2. Add a Text in the SimpleManager init method.
3. Run the code.
4. See the stretched text.

## Media Aid
_If applicable, add screenshots/GIFs/videos to help explain your problem._

![java_p6OxTgQ5ft](https://user-images.githubusercontent.com/49134472/126030259-b6380bd7-4057-4a9c-8886-240c99658ccd.png)

## Additional context
_Additional context not provided above._
I use a Custom class to create the Text.
The code for the class:
```java
package ga.susite.StablerCharacter;

import java.awt.Color;
import java.awt.Font;

import tech.fastj.graphics.game.Text2D;

public class TextInfo {
	Color color;
	Font font;
	
	TextInfo(Color nColor, Font nFont) {
		color = nColor;
		font = nFont;
	}
	
	public Text2D build(String message) {
		return Text2D.create(message).withFont(font).withFill(color).build();
	}
}
```

**Comment by lucasstarsz** [comment]
This is not a bug.
FastJ uses __two__ resolution modifiers: viewer (window) resolution and internal (game) resolution.

The viewer resolution represents the size of the game window -- **changing this does not affect the game content screen size**. The game content will be stetched or shrunk to fit the size of the game window.

On the other hand, internal resolution is the resolution of the game itself. The internal resolution's default size is 1280\*720 -- switching the window's resolution to 800\*600 will make the game shrink down to fit it.
For more information, please look at [FastJEngine#configureInternalResolution](http://api.fastj.me/latest/fastj.library/tech/fastj/engine/FastJEngine.html#configureInternalResolution(tech.fastj.math.Point)) and [FastJEngine#configureViewerResolution](http://api.fastj.me/latest/fastj.library/tech/fastj/engine/FastJEngine.html#configureViewerResolution(tech.fastj.math.Point)).
