### ISSUE TITLE
[Feature Request] Add x11 to the hardware acceleration options

### ISSUE THREAD

**Issue by lucasstarsz** [fastjengine/FastJ#65]
## Is your feature request related to a problem? Please describe.
`HWAccel` currently does not contain an option for Linux's x11 rendering. 

## Solution
- [ ] Add an `X11` option with the x11-based java2d properties to `HWAccel.java`.
- [ ] Restrict access to the option to Linux users only (for an example of this, take a look at `FastJEngine#configureHardwareAcceleration`. This process is already done for `Direct3D`.

**Comment by vlaetansky** [comment]
Can I be assigned on this? I run linux system and I think I know how to do it.

**Comment by lucasstarsz** [comment]
> Can I be assigned on this? I run linux system and I think I know how to do it.
Sure, if you're willing to give it a go! Submit a PR when you're ready to send it to the main repository.
