### ISSUE TITLE
[Source Code]: Rename SupportedFileFormats to SupportedModelFormats

### ISSUE THREAD

**Issue by lucasstarsz** [fastjengine/FastJ#69]
### What's Up?

The `tech.fastj.graphics.io.SupportedFileFormats` class' purpose is to provide a list of supported formats for model reading and writing. It serves its purpose well, but the name can be misleading, and for future purposes is a bit too general. Later on in the future there will be other classes similar to it for other types of files being read, such as audio files.

My recommended solution is to change the class name to `SupportedModelFormats`, since it is much more representative of what the class is for.

### Code of Conduct

- [X] I agree to follow FastJ's Code of Conduct

**Comment by AurumByte** [comment]
Hi there! This seems like the perfect issue to get familiar with the internals... i'll PR the necessary changes :)

**Comment by lucasstarsz** [comment]
Sure thing!
