### ISSUE TITLE
[Source Code]: Add default case to AudioEventListener state checking

### ISSUE THREAD

**Issue by lucasstarsz** [fastjengine/FastJ#70]
### What's Up?

In `tech.fastj.systems.audio.AudioEventListener`, inside the `AudioEventProcessor` Map, the mappings for audio start/stop check the `PlaybackState` in order to process actions. However, the current switch statements do not cover all cases.

I suggest adding default cases to each of the switch statements that throw illegal state exceptions -- these errors should state that the audio state was unexpected and invalid.

### Code of Conduct

- [X] I agree to follow FastJ's Code of Conduct

**Comment by SaadRehmanCS** [comment]
Hi, I would like to work on this

**Comment by lucasstarsz** [comment]
> Hi, I would like to work on this

Go right ahead!
