### ISSUE TITLE
[Documentation]: Broken link to examples

### ISSUE THREAD

**Issue by lines-of-codes** [fastjengine/FastJ#73]
### The Outdated/Incorrect Information

Broken link to an example in FastJ news (in `FastJ 1.5.0 Release` news) in the __Audio Engine__ section, There's this message:
> For the best information, check out [the audio usage example.](https://example.fastj.dev/audio/Main.java)

I clicked the link, And it redirects to https://example.fastj.dev/audio/Main.java page. that redirects to https://github.com/fastjengine/FastJ/tree/main/src/example/java/tech/fastj/example/audio/Main.java which does not exist.

### Suggested Documentation Changes

Fix the link into the correct one.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lucasstarsz** [comment]
It appears there are brokwn links to scene examples and behavior examples as well! Good catch.

**Comment by lucasstarsz** [comment]
With the release of FastJ [1.5.1](https://github.com/fastjengine/FastJ/releases/tag/1.5.1), the `audio` example has been added, and the link should now resolve properly on the website.
