### ISSUE TITLE
[Source Code]: Remove unnecessary cast to float. 

### ISSUE THREAD

**Issue by Sammie156** [fastjengine/FastJ#79]
### What's Up?

From the SonarCloud quality tests, it seems there are some unnecessary casts to float.

### Code of Conduct

- [X] I agree to follow FastJ's Code of Conduct

**Comment by lucasstarsz** [comment]
Ah yes, I remember reading through there a while ago. If you like, feel free to remove them and make a pull request 👍🏾 just make sure you run the unit tests to make sure things work the same without them.
