### ISSUE TITLE
[Bug]: Behaviors are not used in SimpleManager

### ISSUE THREAD

**Issue by lucasstarsz** [fastjengine/FastJ#96]
### What happened?

FastJ's current implementation of `SimpleManager` does not use Behaviors whatsoever. There is no place in which behaviors are updated, or initialized, nor destroyed.

### How to Reproduce the Error

```bash
1. Add a behavior to any game object in a SimpleManager
2. Run the program
3. See error
```

### FastJ Version

1.5.0 (Latest Version)

### Java Version

Java 11, Java 16

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AurumByte** [comment]
Hi there... about this issue, couldn't all game managers extend an abstract game class that contains the `init()`, `update()` and such functions? The main game loop can then run the abstract class functions for which the main game class is passed as an instance..

**Comment by lucasstarsz** [comment]
> Hi there... about this issue, couldn't all game managers extend an abstract game class that contains the `init()`, `update()` and such functions? The main game loop can then run the abstract class functions for which the main game class is passed as an instance..

That's how the current solution runs, yes. The `LogicManager` interface defines the methods that all logic managers need to handle. 
My thoughts are to require methods that handle behaviors, so that they could then be called by the game loop. This works for both `SimpleManager` and `SceneManager` (this can just call the handler methods of the current scene).
